issuer: $DEX_ISSUER_URL

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']
  allowedHeaders: ['x-requested-with']

staticClients:
  - id: daytona
    redirectURIs:
      - '$DAYTONA_API_URL'
      - '$DAYTONA_API_URL/api/oauth2-redirect.html'
      - '$DAYTONA_PROXY_URL/callback'
    name: 'Daytona'
    public: true

oauth2:
  skipApprovalScreen: true
  responseTypes: ["code"]

expiry:
  signingKeys: 6h
  idTokens: 24h
  refreshTokens:
    reuseInterval: 3s
    validIfNotUsedFor: 2160h
    absoluteLifetime: 8760h

enablePasswordDB: true
staticPasswords:
  - email: '$DEX_ADMIN_EMAIL'
    hash: '$DEX_ADMIN_PASSWORD_HASH'
    username: 'admin'
    userID: '08a8684b-db88-4b73-90a9-3cd1661f5466'
